# Generated by Django 4.2.4 on 2023-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_brand_id_remove_product_id_brand_brandid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='BrandId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductId',
        ),
        migrations.AddField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
