# Generated by Django 4.2.4 on 2023-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_brand_brandid_remove_product_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=50),
        ),
    ]
