# Generated by Django 4.2.5 on 2023-09-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('1', 'Fruits'), ('2', 'Vegetables'), ('3', 'Dairy'), ('4', 'Bread'), ('5', 'Cleaners'), ('6', 'Paper Goods'), ('7', 'Personal Care'), ('8', 'Other')], default='1', max_length=20),
        ),
    ]
