# Generated by Django 4.2.4 on 2023-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userType',
            field=models.IntegerField(null=True),
        ),
    ]
