# Generated by Django 4.2.5 on 2023-09-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('createDate', models.DateTimeField()),
                ('deliveryDate', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Shipped'), (3, 'Out For Delivery'), (4, 'Cancelled')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('quanity', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
