# Generated by Django 4.2.5 on 2023-09-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Shipped'), (3, 'Out For Delivery'), (4, 'Cancelled')], default=1),
        ),
    ]
