# Generated by Django 4.2.5 on 2023-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
